cozy/coachCO2

src/components/TripsList.jsx, src/locales/fr.json
- Better french wording
- Use cozy-client method to know if a query has been loaded
=> Minor improvements

src/components/GeoCard.jsx
This was forcing a scroll on some screens
=> fix: Reduce map height

src/components/GeoCard.jsx, src/components/TripItem.jsx
[Based on #14 that should be merged before]
Small UI improvements:
- Display CO2 in GeoCardData
- Display distance before modes in trip list
- Add spacing between CO2 value and RightArrow icon
=> UI improvements

src/components/SectionEditModal/ModeItem.jsx, src/components/Timeline/TimelineSections.jsx, src/components/Trip/TripDialog.jsx, src/components/Trip/TripLayout.jsx, src/components/Trip/TripMap.jsx, src/components/TripItem.jsx, src/components/TripsList.jsx
Attention c'est temporaire et ça n'est pas selon les specs figma (qui n'existent pas pour l'instant). C'est juste pour améliorer l'UX sur desktop, le temps de faire vraiment la partie desktop
=> Show trip detail in a modal on desktop

src/components/BottomSheet/BottomSheet.jsx, src/components/Trip/TripLayout.jsx, src/components/Trip/TripMap.jsx
C'est pas forcément la meilleure manière de faire concernant le BottomSheet, qui a terme va atterrir dans cozy-ui. Une refacto et reflexion plus prodonde sera à faire à ce moment là
=> Set bottomSheet  default position

package.json, src/components/Trip/TripMap.jsx, yarn.lock
fixes the bug of multiple instantiation of the map when editing the trip purpose or resizing the viewport
fix https://github.com/cozy/coachCO2/issues/35
=> feat: Use react-leaflet instead of vanilla leaflet

package.json, src/components/Trip/BottomSheet/PurposeItem.jsx, yarn.lock
=> Use ListItemAvatar from cozy-ui

src/components/Trip/TripView.jsx, src/components/TripsList.jsx, src/lib/trips.js, src/lib/trips.spec.js, test/mockTrip.js
to remove multiple map inside the function
fix https://github.com/cozy/coachCO2/issues/44
=> Optimize transformTimeSeriesToTrips()

CHANGELOG.md, README.md, package.json, yarn.lock
use cozy-ach to import fixtures
=> feat: Add fixtures

.travis.yml, CONTRIBUTING.md, README.md
=> refactor: Replace `paultranvan` by `cozy` in repo urls

CODEOWNERS , package.json, yarn.lock
Update des packages cozy afin d'avoir une app avec des packages récents
=> Update cozy packages

package.json, test/jestLib/setup.js, yarn.lock
Unused and blocking for future updates of React
=> feat: Remove enzyme package

jsconfig.json
Added jsconfig file for better support with editors (autocomplete, link between files, ...)
=> feat: Add jsconfig file

src/components/Analysis/AnalysisListItem.jsx, src/components/Analysis/AnalysisListItem.spec.js
Petit loupé des besoins sur la PR précédente : https://github.com/cozy/coachCO2/pull/68
=> feat: Add chevron to analysis items for better UX

src/components/Titlebar.jsx
Removal of the absolute style that generates bugs on some pages
=> fix: Titlebar UI

src/components/Views/Settings.jsx, src/locales/en.json, src/locales/fr.json
Pending resolution of this issue #61
We still want to see the account selected in the SelecBox component
Added a label for export to have a better UI
=> fix: SelectBox component & wording

src/components/Analysis/Modes/ModesList.jsx, src/components/Analysis/Purposes/PurposesList.jsx, src/components/Analysis/Purposes/PurposesList.spec.js, src/queries/queries.js
ça ne concerne que le fix par rapport à l'account, pas le fait d'utiliser un noLimit
=> feat: Analysis page use account to get the trips

README.md
This format is quite complex and includes lot of useless data with
redundancy. This sums up the relevant information, altough not
exhaustive.
=> docs: Add documentation for GeoJSON content

CHANGELOG.md, src/components/Trip/BottomSheet/BottomSheetContent.jsx, src/components/TripItem.jsx
=> refactor: Use `timeserie` instead of `trip` to show startDate / endDate

CHANGELOG.md, src/components/EditDialogs/ModeEditDialog/ModeEditDialog.jsx, src/components/EditDialogs/PurposeEditDialog/PurposeEditDialog.jsx, src/components/Timeline/TimelineSections.jsx, src/components/Trip/BottomSheet/PurposeItem.jsx, src/components/Views/ModeAnalysis.jsx, src/components/Views/PurposeAnalysis.jsx
locales keys are in upper cases : https://github.com/cozy/coachCO2/blob/master/src/locales/en.json#L20
Quick fix for a bug in prod. We should rewrite the tests to avoid mocking everything but only the necessary, to be able to test more things like the locales...
=> fix: Locales to get trip purpose/mode

README.md
This is saved in the trip properties
=> docs: Add manual purpose to GeoJSON example

CHANGELOG.md, src/components/ExportCSV/CsvExporter.jsx, src/components/ExportCSV/ExportDialog.jsx, src/hooks/useExportTripsToCSV.jsx, src/hooks/useExportTripsToCSV.spec.jsx, src/lib/exportTripsToCSV.js, src/lib/exportTripsToCSV.spec.js, src/queries/queries.js
Refactor and limit export by account.
=> feat: Add useExportTripToCSV hook

package.json, src/queries/queries.js, yarn.lock
Now https://github.com/cozy/cozy-client/pull/1193 is merged, partial indexes should be fixed
=> Fix partial index

CHANGELOG.md, src/components/Providers/TripProvider.jsx, src/components/Providers/helpers.js, src/components/Providers/helpers.spec.js
Already reviewed with https://github.com/cozy/coachCO2/pull/171
=> fix: Timeline order

package.json, scripts/remove-purposes.js, scripts/save-random-trip.js
Add 2 scripts useful for dev purpose
=> Add scripts for dev

CHANGELOG.md
forgotten here https://github.com/cozy/coachCO2/pull/186 🤦 💢
=> docs: Changelog

CHANGELOG.md, src/components/Analysis/Modes/LoadedModesList.jsx, src/components/Analysis/Modes/LoadedModesList.spec.js, src/components/Analysis/Purposes/LoadedPurposesList.jsx, src/components/Analysis/Purposes/LoadedPurposesList.spec.js, src/components/AppRouteur.jsx, src/components/Trip/TripDialogMobile.jsx, src/components/TripItem.jsx, src/components/TripsList.jsx, src/components/Views/ModeAnalysis.jsx, src/components/Views/PurposeAnalysis.jsx, src/lib/recurringPurposes.js, src/lib/recurringPurposes.spec.js
On souhaite release très prochainement la 
v0.9.0 et on risque par la suite de mettre le 
développement de l'app en pause quelque temps. 
Par conséquent on intègre dans la prochaine 
release les quelques fixes qui ont été fait 
récemment, sans attendre la release suivante.
=> Get some features from 0.10.0 to 0.9.0

README.md
```
* Add coachco2.bikegoal.enabled flag in documentation
```
=> docs: Add coachco2.bikegoal.enabled flag

.eslintrc.json, tsconfig.json
```
* Add typescript config
```
=> Add typescript config

src/components/Goals/BikeGoal/BikeGoalAlertManager.jsx, src/components/Views/Trips.jsx
to be more specific and consistant with DaccManager
```
* Rename BikeGoal in BikeGoalAlertManager
```
=> refactor: Rename BikeGoal in BikeGoalAlertManager

src/components/AppProviders.jsx, src/components/Goals/BikeGoal/BikeGoalDialogMobile.jsx, src/components/Goals/BikeGoal/BikeGoalViewDesktop.jsx, src/components/Goals/BikeGoal/DateSelector/BikeGoalDateSelector.jsx, src/components/Goals/BikeGoal/DateSelector/DesktopButton.jsx, src/components/Goals/BikeGoal/DateSelector/MobileButton.jsx, src/components/Providers/BikeGoalDateProvider.jsx, src/components/Trip/BottomSheet/InfoBlock.jsx, src/components/Views/BikeGoal.jsx, src/lib/timeseries.js, src/lib/timeseries.spec.js
On souhaite pouvoir changer l'année de référence pour la vue qui liste les trajets de l'objectif vélo
```
* Add a date selector for bike goal
```
=> feat(BikeGoal): Add a date selector

.gitignore, package.json, yarn.lock
To benefit from the correction in the commit konnectors/libs@6f8ae10
And add the files generated by the `service:timeseriesWithoutAggregateMigration` command to the `.gitignore` file
=> feat: Update cozy-jobs-cli

src/components/Goals/BikeGoal/BikeGoalAlert.jsx, src/components/Goals/BikeGoal/BikeGoalAlertSuccess.jsx, src/components/Goals/BikeGoal/Certificate/CertificateGenerationContent.jsx, src/components/Goals/BikeGoal/helpers.js
`BikeGoalAbout` is already importing it under the correct name.
(changelog omitted)
=> Fix name of `getBountyAmount` helper

package.json, src/components/AppProviders.jsx, src/components/AppRouter.jsx, src/components/Goals/BikeGoal/Edit/EditModal.jsx, src/components/Goals/BikeGoal/Edit/EditModalContent.jsx, src/components/Goals/BikeGoal/Edit/ModificationModalContent.jsx, src/components/Goals/BikeGoal/OptionSelector/BikeGoalOptionSelector.jsx, src/components/Views/BikeGoalEdit.jsx, src/locales/en.json, src/locales/fr.json, src/queries/queries.js, yarn.lock
```
* Add modal to edit bike goal
```
=> Add possibility to edit bike goal

src/components/Goals/BikeGoal/BikeGoalSummary.jsx, src/components/Views/BikeGoalOnboardingSteps/BikeGoalOnboardingConclusion.jsx, src/components/Views/Trips.jsx
```
* Open the bike goal details when clicking on the bike goal summary
```
=> Open the bike goal details when clicking on the summary

src/components/Goals/BikeGoal/Certificate/CertificateGeneration.jsx, src/components/Views/BikeGoalOnboardingSteps/BikeGoalOnboardingComparison.jsx, src/locales/en.json, src/locales/fr.json
=> BikeGoal: some fixes on certificate generation and DACC

src/components/CO2EmissionsChart/CO2EmissionsChart.jsx, src/components/CO2EmissionsChart/helpers.js, src/components/CO2EmissionsChart/helpers.spec.js, src/components/DaccManager/CO2EmissionDaccManager.jsx, src/components/DaccManager/CO2EmissionDaccManager.spec.js, src/hooks/useFetchDACCAggregates.jsx, src/hooks/useFetchDACCAggregates.spec.jsx, src/lib/dacc.js, src/lib/dacc.spec.js
=> `CO2Emission` setting is named `sendToDACC`, not `sendToDacc`

CODEOWNERS, src/components/Goals/BikeGoal/DateSelector/helpers.spec.js
=> Update code owners

.tx/config, CONTRIBUTING.md, README.md, transifex.yml
=> chore: Add transifex

transifex.yml
```
* Fix transifex configuration for github integration
```
=> chore: Fix transifex configuration for github integration

package.json, yarn.lock
```
* Update cozy-scripts from 6.3.11 to 8.0.3
```
=> chore: Update cozy-scripts from 6.3.11 to 8.0.3

.github/auto-merge.yml
```
* Add auto-merge config
```
=> chore: Add auto-merge config

README.md, scripts/save-random-trip.js
This pull request expands the documentation for importing fixtures in the application. The goal is to help developers fix common issues encountered when installing fixtures on a blank environment. The updates include:
- Adding instructions for installing the latest version of ACH
- Providing an alternative command for importing fixtures with a custom URL
- Updating the development URL in `konnector-dev-config.json`
- Adding a necessary document to the `io.cozy.accounts` database
- Handling invalid JWT tokens when running a service
By providing clearer instructions and addressing common issues, this PR aims to make it easier for developers to work with fixtures in the project.
=> Improve Fixture Documentation

src/components/Views/Settings.jsx, src/locales/en.json, src/locales/fr.json
```
* Move debug switch to specific category(77e557c)
```
=> feat: Move debug switch to specific category

src/locales/en.json, src/locales/fr.json
```
* Change of onboarding wording
```
=> feat: Change of onboarding wording

package.json, src/components/Trip/TripDialogDesktop.jsx, src/components/Trip/TripDialogMobile.jsx, yarn.lock
```
* Add end date in trip dialog
```
=> Add end date in trip dialog

src/lib/timeseries.js, src/lib/timeseries.spec.js
On affiche maintenant les données du dernier mois dans le graphique des 
emission CO²
```
* Add last month in chart emission data computing
```
=> feat: Add last month in chart emission data computing

src/components/Analysis/Modes/LoadedModesList.jsx, src/components/Analysis/Purposes/LoadedPurposesList.jsx
```
* Reverse sort order on analysis pages (mode & purpose)
```
=> feat: Reverse sort order on analysis pages (mode & purpose)

src/locales/en.json, src/locales/fr.json
```
*
* Add missing locales for modes
*
```
=> fix: Add missing locales

src/queries/queries.js, src/queries/queries.spec.js
```
* The recent addition of transport modes `bicycling electric` & `scooter electric` must be taken into account for the SMP.
```
=> feat: Add modes to the "SMP" query

src/components/AppRouter.jsx, src/components/Goals/BikeGoal/BikeGoalAlertSuccess.jsx
```
* Certificate generation does not redirect to the correct page
```
=> fix: Certificate generation does not redirect to the correct page

package.json, yarn.lock
```
* Upgrade cozy-ui from `93.1.0` to `93.2.0` ([6d4447f](https://github.com/cozy/cozy-ui/commit/6d4447f))
```
=> feat: Upgrade cozy-ui from `93.1.0` to 93.2.0

src/queries/queries.js
A new openPath konnector is coming that should eventually replace tracemob.
Let's keep both slugs for now, to ensure retro-compatibility
```
* Get accounts from openpath konenctor
*
*
```
=> feat: Support for openpath konnector

src/components/Analysis/AnalysisListItem.jsx, src/components/Analysis/AnalysisListItem.spec.js
```
* Hide unused mode and purpose on Analysis page
```
=> feat: Hide unused mode and purpose on Analysis page

src/components/ContactToPlace/helpers.js, src/components/ContactToPlace/helpers.spec.js, src/components/Timeline/TimelineNode.jsx, src/components/Trip/BottomSheet/BottomSheetContent.jsx, src/lib/timeseries.js, src/locales/en.json, src/locales/fr.json
- Si le contact est = "moi (myself)" et que le libellé est = "domicile" => on affiche la valeur "Chez moi".
- Si le contact est = "moi" et qu'on a le libellé Travail => on affiche le Libellé "Travail". 
- Si le contact est = "moi" et qu'on a un libellé perso => on affiche le "Libellé perso". 
- Si le contact est = "moi" et qu'on a pas de libellé => on affiche le nom du Contact cad "moi(myself)". 
- Si le contact n'est pas moi et que le libellé est = "domicile" => on affiche "Chez Contact".
- Si le contact n'est pas moi et que le libellé est = "Travail" => on affiche "Contact (Travail)".
- Si le contact n'est pas moi et qu'on a un libellé perso => on affiche "Contact + (Libellé perso)".
- Si le contact n'est pas moi et qu'on a pas de libellé => on affiche le "nom du Contact".
=> Show a place following a certain logic

src/components/Trip/TripDialog.jsx, src/lib/timeseries.js
```
* Display start date instead en date in trip details (modal)
```
=> feat: Display start date instead en date in trip details (modal)

src/components/EditDialogs/ModeEditDialog/ModeEditDialog.jsx, src/locales/en.json, src/locales/fr.json
```
* Add tooltip on mode edit dialog title
```
=> feat: Add tooltip on mode edit dialog title

src/components/Trip/BottomSheet/InfoBlock.jsx, src/components/Trip/TripDialogDesktopContent.jsx, src/components/Trip/TripDialogMobileContent.jsx
```
* Adjust info block style in trip dialog
```
=> fix: Adjust info block style in trip dialog

src/components/Goals/BikeGoal/BikeGoalAlert.jsx, src/components/Goals/BikeGoal/BikeGoalOnboardingSteps/BikeGoalOnboardingComparison.jsx, src/components/Goals/BikeGoal/BikeGoalOnboardingSteps/BikeGoalOnboardingConclusion.jsx, src/components/Goals/BikeGoal/Edit/ModificationModalContent.jsx, src/components/Views/BikeGoalAbout.jsx, src/locales/en.json, src/locales/fr.json
```
* Adjust bike goal onboarding wordings
```
=> Change onboarding wordings

package.json, src/components/EmptyContent/EmptyContentManager.jsx, src/components/EmptyContent/InstallKonnector.jsx, src/components/EmptyContent/SpinnerOrEmptyContent.jsx, src/components/EmptyContent/SpinnerOrEmptyContent.spec.jsx, src/components/EmptyContent/helpers.js, src/components/EmptyContent/helpers.spec.js, src/components/Views/BikeGoal.jsx, src/components/Views/Trips.jsx, src/locales/en.json, src/locales/fr.json, src/queries/queries.js, yarn.lock
Selon si il n'y a aucun compte source, si la feature de geoloc est 
possible, s'il y a des déplacements sur d'autres comptes sources que celui 
sélectionné etc. On affiche une page "empty" adéquate. 
⚠️  **à merger après validation svp**
```
* Displays a specific page when there is no trip
```
=> Better management of cases where there is no trip

README.md, src/components/helpers.js, src/components/helpers.spec.js, src/constants.js, src/lib/metrics.js, src/lib/timeseries.spec.js, src/locales/en.json, src/locales/fr.json
```
* Add "Tramway" as a mode of transport
```
=> Feat: Add tramway mode of transport

src/components/Analysis/Modes/ModesList.jsx, src/components/Analysis/Purposes/PurposesList.jsx, src/components/Analysis/Purposes/PurposesList.spec.js, src/components/Views/ModeAnalysis.jsx, src/components/Views/PurposeAnalysis.jsx
```
* Move analysis SelectDates to show only if the is a content
```
=> feat: Move analysis SelectDates to show only if the is a content

src/components/Goals/BikeGoal/Certificate/CertificateGenerationContent.jsx, src/components/Goals/BikeGoal/helpers.js, src/components/Goals/BikeGoal/helpers.spec.js
```
* For certificate, use name of bikegoal user instead currentuser
```
=> feat: For certificate, use name of bikegoal user instead currentuser

src/components/Goals/BikeGoal/BikeGoalList.jsx, src/components/Goals/BikeGoal/BikeGoalManager.jsx, src/locales/en.json, src/locales/fr.json
```
* Add empty content on Bike Goal page
```
=> Add empty content for BikeGoal page

src/components/AccountSelector.jsx, src/components/AppVersionNumber.jsx, src/components/CO2EmissionDaccAlertSwitcher.jsx, src/components/CO2EmissionDaccSwitcher.jsx, src/components/ExportCSV/CsvExporter.jsx, src/components/GeolocationTracking/GeolocationTrackingSwitcher.jsx, src/components/Goals/BikeGoal/BikeGoalAlertSuccessSwitcher.jsx, src/components/Goals/BikeGoal/BikeGoalAlertSwitcher.jsx, src/components/Goals/BikeGoal/BikeGoalDaccSwitcher.jsx, src/components/Goals/BikeGoal/BikeGoalOnboardedSwitcher.jsx, src/components/Goals/BikeGoal/BikeGoalSwitcher.jsx, src/components/Views/Settings.jsx, src/locales/en.json, src/locales/fr.json
```
* Refresh look of Settings page
```
=> feat: Refresh look of Settings page

.travis.yml, src/locales/fr.json
```
* Change regex for Travis branches build
```
=> Travis branches build

src/components/EmptyContent/helpers.js, src/components/Goals/BikeGoal/BikeGoalAlertSuccess.jsx, src/components/Goals/BikeGoal/BikeGoalOnboardingSteps/BikeGoalOnboardingComparison.jsx, src/components/Goals/BikeGoal/BikeGoalOnboardingSteps/BikeGoalOnboardingIntroduction.jsx, src/components/Goals/BikeGoal/BikeGoalSummaryDaccItems.jsx, src/components/Goals/BikeGoal/Certificate/CertificateGenerationContent.jsx, src/components/Goals/BikeGoal/Edit/ModificationModalContent.jsx, src/components/Goals/BikeGoal/helpers.js, src/components/Views/BikeGoalAbout.jsx, src/lib/daccBikeGoal.js, src/locales/en.json, src/locales/fr.json
```
* Bike goal : Change wording according to `bountyAmount`
* Bike goal : Change wording according to `sourceName`
* Remove useless call to `getBountyAmount`
* Remove throwing error if bountyAmount isn't set
```
=> Some changes after release

src/components/TripsList.jsx, src/locales/en.json, src/locales/fr.json
```
* Add tooltip on home when geolocation is available but disabled
```
=> feat: Add tooltip when geoloc is disabled

package.json, src/components/ExportCSV/CsvExporter.jsx, src/components/ExportCSV/ExportDialog.jsx, src/components/GeolocationTracking/GeolocationLogsExporter.jsx, src/components/GeolocationTracking/GeolocationTrackingSettings.jsx, src/components/Views/Settings.jsx, src/locales/en.json, src/locales/fr.json, yarn.lock
```
* Move geolocation export log button from admin to export section
* Replace button style of csv export by listItem
* Upgrade cozy-ui 100.0.0 to 100.1.0
```
=> feat(Geolocation): Move export log button from admin to export section

src/components/ContactToPlace/ContactToPlaceDialogContent.jsx, src/components/ContactToPlace/helpers.js, src/components/ContactToPlace/helpers.spec.js, src/components/EditDialogs/ModeEditDialog/helpers.spec.js, src/components/Timeline/TimelineNode.jsx, src/components/Trip/TripDialog.jsx, src/components/TripItem.jsx, src/lib/timeseries.js, src/locales/en.json, src/locales/fr.json
```
* Now throw explicit error if  undefined `series`
* Now use default start/end place display name if not computed
```
=> Now use default start/end place display name if not computed

src/components/Trip/TripDialog.jsx, src/components/Trip/TripTitleEditDialog.jsx, src/lib/timeseries.js, src/lib/timeseries.spec.js, src/locales/en.json, src/locales/fr.json, src/queries/queries.js, src/queries/queries.spec.js
relative to https://github.com/cozy/cozy-doctypes/pull/244
```
* Add possibility to set a trip title manually
```
=> Add possibility to set a trip title manually

package.json, src/components/Goals/BikeGoal/Certificate/helpers.js, src/components/helpers.js, src/lib/dacc.js, src/lib/daccBikeGoal.js, src/lib/daccMonthlyCO2.js, src/lib/exportTripsToCSV.js, src/lib/recurringPurposes.js, src/targets/browser/setupApp.jsx, src/targets/services/daccBikeGoal.js, src/targets/services/daccMonthlyCO2.js, src/targets/services/recurringPurposes.js, src/targets/services/timeseriesWithoutAggregateMigration.js, yarn.lock
```
* Replace `cozy-logger` by `cozy-minilog`
* Add Sentry
```
=> Feat: Use minilog instead cozy logger & add Sentry

src/components/ListWrapper.jsx, src/components/SelectDates/SelectDatesWithLoader.jsx, src/components/SelectDatesWrapper.jsx, src/components/Trip/TripDialog.jsx, src/components/Trip/TripTitleEditDialog.jsx, src/components/Views/BikeGoal.jsx, src/components/Views/Trips.jsx, src/lib/timeseries.js, src/lib/timeseries.spec.js, src/locales/en.json, src/locales/fr.json, src/queries/queries.js, src/queries/queries.spec.js
```
* Replace spinners by skeletons on Trips, BikeGoal and Analysis pages
```
=> Replace spinners by skeletons on Trips, BikeGoal and Analysis pages

.travis.yml
```
* Bump to node 20
* Remove travis caches
```
=> Chore: Remove travis caches & Bump to node 20

package.json, src/components/GeolocationTracking/GeolocationTrackingSwitcher.jsx, src/components/GeolocationTracking/helpers.js, src/components/GeolocationTracking/helpers.spec.js, src/components/Providers/GeolocationTrackingProvider.jsx, yarn.lock
```
* Display a paywall when trying to enable geolocation tracking if geolocation quota exceeded
```
Linked to https://github.com/cozy/cozy-flagship-app/pull/1090. Do not fail if flagship app is not up to date.
=> Add geolocation quota paywall

src/components/AccountSelector.jsx, src/components/CO2EmissionDaccAlertSwitcher.jsx, src/components/CO2EmissionDaccSwitcher.jsx, src/components/EmptyContent/ChangeAccount.jsx, src/components/EmptyContent/GPSStandby.jsx, src/components/ExportCSV/CsvExporter.jsx, src/components/FAQ/FAQHelp.jsx, src/components/FAQ/FAQItem.jsx, src/components/GeolocationTracking/GeolocationLogsExporter.jsx, src/components/GeolocationTracking/GeolocationTrackingSettings.jsx, src/components/GeolocationTracking/GeolocationTrackingSwitcher.jsx, src/components/Goals/BikeGoal/BikeGoalAlertSuccessSwitcher.jsx, src/components/Goals/BikeGoal/BikeGoalAlertSwitcher.jsx, src/components/Goals/BikeGoal/BikeGoalDaccSwitcher.jsx, src/components/Goals/BikeGoal/BikeGoalOnboardedSwitcher.jsx, src/components/Goals/BikeGoal/BikeGoalSwitcher.jsx, src/components/Views/Settings.jsx, src/locales/en.json, src/locales/fr.json
```
* Add FAQ link to Settings page
* Add FAQ link helper to the bottom of certain pages to assist the user
```
=> feat: Add FAQ link components

src/components/Views/Settings.jsx
Removing unnecessary margin from new page style
=> fix: Style of Settings page

package.json, src/components/helpers.js, src/lib/dacc.js, src/lib/daccBikeGoal.js, src/lib/daccMonthlyCO2.js, src/lib/recurringPurposes.js, src/targets/services/daccBikeGoal.js, src/targets/services/daccMonthlyCO2.js, src/targets/services/recurringPurposes.js, src/targets/services/timeseriesWithoutAggregateMigration.js, yarn.lock
A previous commit replaced cozy-logger by cozy-minilog, but in services you must keep cozy-logger.
=> feat: Add cozy-logger for services

src/components/GeolocationTracking/GeolocationTrackingSwitcher.jsx
related: https://github.com/cozy/coachCO2/pull/357
=> fix: Horizontal scrolling on Settings page

manifest.webapp, src/components/GeolocationTracking/helpers.js, src/constants.js, src/doctypes/index.js, src/lib/dacc.js, src/lib/daccCentreValDeLoireExpe.js, src/lib/daccCentreValDeLoireExpe.spec.js, src/lib/recurringPurposes.js, src/lib/recurringPurposes.spec.js, src/lib/types.js, src/locales/en.json, src/queries/queries.js, src/targets/services/daccCentreValDeLoireExpe.js
Those measures are meant for an experimentation with Centre Val de
Loire.
It aggregates values such as CO2 or distance for the current month, and
group them based on the mode, school (when relevant), and user type
(when relevant).
Note the school matching relies on a pre-defined contacts group name,
including contacts' schools with geo information.
=> [DAT-2] DACC measures for experimentation

package.json, yarn.lock
This update fixes a translation issue into the CoachCO2 paywall
```
* Update cozy-ui from 101.1.1 to 101.2.0
```
=> [VO-272] feat: Update cozy-ui from 101.1.1 to 101.2.0

src/lib/daccCentreValDeLoireExpe.js, src/lib/daccCentreValDeLoireExpe.spec.js
Backport https://github.com/cozy/coachCO2/pull/378
=> feat: Log errors if negative values are met

README.md, package.json, scripts/drop-account.js, scripts/drop-accounts.js, scripts/helpers.js, scripts/remove-purposes.js, scripts/save-account.js, scripts/save-random-trip.js
```
* Add some scripts to manage data locally
```
=> Chore: Add some scripts to manage data locally

src/targets/browser/setupApp.jsx
```
* Forces the choice “All sources” when loading the app
```
=> feat: Forces the choice “All sources” when loading the app

src/components/GeolocationTracking/LocationDisabledDialog.jsx, src/locales/en.json, src/locales/fr.json
No changelog (same as https://github.com/cozy/coachCO2/pull/393)
=> fix: Update wording of location disabled dialog

src/components/SelectDatesWrapper.jsx
```
* 
* Fix Analysis performances issue
*
```
=> fix: Set correct limit

package.json, yarn.lock
```
* Upgrade cozy-ach to 1.51.0
```
=> feat: Upgrade cozy-ach to 1.51.0

scripts/helpers.js, scripts/save-random-trip.js
This property exists in real but was missing in the fixtures.
```
* Add captureDevice property to trip fixture
```
=> chore: Add captureDevice property to trip fixture

src/components/EmptyContent/EmptyContentManager.jsx, src/components/EmptyContent/GPSStandby.jsx
...with a new account without trips.
Link with : https://github.com/cozy/coachCO2/pull/392
=> fix: Add a missing conditions displayed the correct screen

app.config.js, package.json, src/components/AppLayout.jsx, yarn.lock
=> chore: Add CozyDevTools

src/components/TripItem.jsx
If not from the current year
```
* Adding the year to the trips subHeaders
```
=> feat: Adding the year to the trips subHeaders

src/lib/geolocationQuota/notificationHelper.js, src/lib/openpath/openpath.js, src/locales/fr.json
Fix of https://github.com/cozy/coachCO2/pull/388
=> Fix notification quota text title and text content

src/components/EmptyContent/InstallApp.jsx, src/locales/en.json, src/locales/fr.json
```
* Change the text when there are no trips, in Desktop mode
```
=> Feat: Change text when have no trips on Desktop

src/lib/openpath/openpath.js
This will ease debugging
```
* Retain openpath trips for 30 days rather than 7
*
*
```
=> feat: Retain openpath trips for 30 days

jest.config.js, src/lib/geolocationQuota/lib.js, src/lib/geolocationQuota/lib.spec.js
Some tests for https://github.com/cozy/coachCO2/pull/388 to **explicit expected behavior**.
=> Add some tests about geolocation quota notification

src/components/ContactToPlace/helpers.js, src/components/ContactToPlace/helpers.spec.js
```
* Associating to a trip a contact with an existing address wasn't working
```
=> fix(ContactToPlace): Associating a contact with an existing address

package.json, src/lib/recurringPurposes.js, src/targets/browser/index.ejs, yarn.lock
The contact list was very slow when dealing with thousands of contacts.
This is now fixed thanks to https://github.com/cozy/cozy-ui/pull/2646
```
* [Improve contact list performances](https://github.com/cozy/coachCO2/commit/9b6ac1890ad2660108c928382d73fb115201e386)
* [Distance-based recurring loop trips](https://github.com/cozy/coachCO2/commit/0bd8f0f095f03f5da1f958f466134a55e6a9917a)
* 
*
```
=> Recurring address perfs

src/components/ContactToPlace/helpers.js
```
*
* Fix address label matching
*
```
=> [VER-653] fix: Correct contact matching

src/constants.js, src/lib/recurringPurposes.js, src/lib/recurringPurposes.spec.js
```
* Better handling of recurring loop trips: use distance and time filters 
*
*
```
=> Better handling of recurring loop trips

package.json, src/components/AppProviders.jsx, yarn.lock
```
* Add realtime on io.cozy.settings
```
=> feat: Upgrade cozy-ui and add realtime on io.cozy.settings

src/components/ContactToPlace/helpers.spec.js, src/locales/en.json, src/locales/fr.json
A groundbreaking improvement.
```
* Add emoji for home location
*
*
```
=> feat: Add emoji for home location
