cozy/coachCO2

- src/components/TripItem.jsx
- src/components/trips.js
- src/components/trips.spec.js
- src/constants/const.js
For each trip, compute the CO2 total, based on the distance and
transport mode.
We rely on constants values for each mode, all taken from the ADEME
database: https://www.bilans-ges.ademe.fr/
Note that most of those values are approximations, as many factors can
imapct the CO2 production (vehicle type and age, conductor usage, number
of passengers, etc).
> feat: Add trip carbon computation 

- src/components/BottomSheet/BottomSheet.jsx
Dragging down the bottomSheet on Safari triggered the pull-down-to-refresh behavior
> feat: Add BottomSheet hack to prevent pull-down-to-refresh

- package.json
- src/targets/browser/index.jsx
- test/AppLike.jsx
- yarn.lock
In order to make all **Cozy Apps** compatible with **Amirale**, we have to wrap them in the `cozy-intent` provider.
To do so, we have to:
- Add `cozy-intent`
- Upgrade `cozy-device-helper` to the latest version (necessary for `cozy-intent` as its peer dependency)
- Wrap the application at the highest possible level with the `<WebviewIntentProvider />`
> feat: Implement WebviewIntentProvider

- src/components/TripItem.jsx
In the case of 4 or more trips, the space between the icons was not good anymore
Before:
After:
> fix: Space between trips icons

- src/components/EditDialogs/PurposeEditDialog/helpers.js
- src/components/EditDialogs/PurposeEditDialog/helpers.spec.js
- src/lib/__snapshots__/timeseries.spec.js.snap
- src/lib/timeseries.js
- src/lib/timeseries.spec.js
- src/lib/trips.js
- src/lib/trips.spec.js
On corrige ici les comportements à la "marge" : les modes de transport non pris en charge par l'app (qui fallback maintenant sur unknown), des modes de transport stocké en base en lowercase
- pas de changelog modifié car il n'y a pas de différence avec la release précédent, les fix concernent la même release
> Fix some behavior with analysis

- src/components/Analysis/AnalysisListItem.jsx
- src/lib/trips.js
- src/lib/trips.spec.js
Display of 2 decimal of the CO2 **percentage** for more accuracy
(Except if the decimal part is "00")
Before:
After:
> fix: Display 2 decimal of CO2 percent

- CHANGELOG.md
- jest.config.js
- package.json
- src/components/Analysis/Modes/ModesList.jsx
- src/components/Analysis/Purposes/PurposesList.jsx
- src/components/Analysis/Purposes/PurposesList.spec.js
- src/components/Providers/SelectDatesProvider.jsx
- src/components/SelectDates.jsx
- src/components/SelectDates/DropdownButton.jsx
- src/components/SelectDates/DropdownMenuButton.jsx
- src/components/SelectDates/DropdownMenuButton.spec.js
- src/components/SelectDates/EmptySelectDates.jsx
- src/components/SelectDates/SelectDates.jsx
- src/components/SelectDates/SelectDates.spec.js
- src/components/SelectDates/SelectDatesWithLoader.jsx
- src/components/SelectDates/__snapshots__/helpers.spec.js.snap
- src/components/SelectDates/helpers.js
- src/components/SelectDates/helpers.spec.js
- src/components/SelectDatesWrapper.jsx
- src/components/Views/ModeAnalysis.jsx
- src/components/Views/ModeAnalysis.spec.js
- src/components/Views/PurposeAnalysis.jsx
- src/components/Views/PurposeAnalysis.spec.js
- src/hooks/useAllTimeseriesByAccount.js
- src/hooks/useAllTimeseriesByAccount.spec.js
- src/queries/queries.js
- test/AppLike.jsx
- test/jestLib/setup.js
- test/jestLib/setupAfterEnv.js
- yarn.lock
On a passé 3 jours de plus que l'estimation sur cette feature qui a demandé pas mal d'energie, soyez assez "light" sur les retours svp  🙏🙏🙏 ;)
Les composants suivants devraient être dans cozy-ui :
- DropdownButton
- DropdownMenuButton
- SelectDates
- SelectDatesWithLoader
- EmptySelectDates
Comme le SelectDates est censé être dans cozy-ui, il a été construit comme tel (il attend des props d'un context qui vient de l'app)
> Add date filter for analysis pages

- src/components/TripItem.jsx
- src/lib/metrics.js
- src/lib/metrics.spec.js
- src/lib/trips.js
- src/lib/trips.spec.js
On the TripsList by mode, the CO2 value per trip must only indicate the CO2 generated by the mode of transport concerned
> fix: Display correct CO2 value

- src/lib/exportTripsToCSV.js
The file was correctly saved in .csv in Drive, but was turned into .css when downloading it
> fix: Typo in CSV content-type

- CHANGELOG.md
- manifest.webapp
- src/components/Providers/AccountProvider.jsx
- src/components/Providers/SelectDatesProvider.jsx
- src/components/Providers/TripProvider.jsx
- src/components/Providers/helpers.js
- src/components/Providers/useAccountForProvider.js
- src/components/Providers/useAccountForProvider.spec.jsx
- src/components/Views/Settings.jsx
- src/components/Views/Trips.jsx
- src/doctypes/index.js
- src/hooks/useAllTimeseriesByAccount.js
- src/hooks/useAllTimeseriesByAccount.spec.js
- src/queries/queries.js
On stocke le count sélectionné dans un doctype io.cozy.coachco2.settings afin de conserver l'info même après un hard refresh de l'app
> AccountProvider set account into settings doctype

- src/components/Providers/TripProvider.jsx
- src/components/Providers/helpers.js
- src/components/Providers/helpers.spec.js
Temporary fix, waiting for a bigger refactor.
We don't want to save a `timeseries` document with the `aggregation` prop
> fix: Remove aggregation prop before save doc

- src/components/TripItem.jsx
pour éviter un retour à la ligne entre la valeur et l'unité du CO2
> feat: Add nowrap on TripItem CO2

- CHANGELOG.md
- src/components/Analysis/Modes/ModesList.jsx
- src/components/Analysis/Purposes/PurposesList.jsx
- src/components/SelectDatesWrapper.jsx
Si on a plus de document à fetcher que le limitBy indiqué dans la query, useFullyLoadedQuery va fetchMore après la pagination. Or en faisant ça, le fetchStatus passe de loaded à loading (après être passé initialement de loading à loaded). Si on ne fait que checker le fetchStatus dans la vue (via isQueryLoading) on passe donc d'un true à false puis true.
> fix: Check hasMore on result for useFullyLoadedQuery to avoid blinking

- CHANGELOG.md
- src/components/Analysis/Modes/LoadedModesList.jsx
- src/components/Analysis/Purposes/LoadedPurposesList.jsx
- src/components/EditDialogs/ModeEditDialog/ModeEditDialog.jsx
- src/components/EditDialogs/ModeEditDialog/helpers.js
- src/components/EditDialogs/ModeEditDialog/helpers.spec.js
- src/components/EditDialogs/PurposeEditDialog/PurposeEditDialog.jsx
- src/components/EditDialogs/PurposeEditDialog/helpers.js
- src/components/EditDialogs/PurposeEditDialog/helpers.spec.js
- src/components/Providers/TripProvider.jsx
- src/components/Timeline/TimelineSections.jsx
- src/components/Trip/BottomSheet/BottomSheetContent.jsx
- src/components/Trip/BottomSheet/BottomSheetHeader.jsx
- src/components/Trip/TripDialogDesktop.jsx
- src/components/Trip/TripDialogMobile.jsx
- src/components/Trip/TripMap.jsx
- src/components/TripItem.jsx
- src/components/TripsList.jsx
- src/components/Views/Trip.jsx
- src/components/Views/Trips.jsx
- src/lib/exportTripsToCSV.js
- src/lib/timeseries.js
- src/lib/trips.js
Nous avons plusieurs notions et objets manipulés aujourd'hui dans CCO2 ce qui nous embrouille plus qu'autre chose. L'objectif à terme et de n'utiliser que le timeserie, qui est le doc tel que fetché depuis couch.
Ceci est une première étape low cost
fix https://github.com/cozy/coachCO2/issues/94
> Remove `geojson` object and use timeserie instead of trip

- CHANGELOG.md
- src/components/TripItem.jsx
part of https://github.com/cozy/coachCO2/issues/26
Force not to render the tripItem if the rev does not change. For the record, we can't change the data without using save.client, so the rev is bound to change.
This greatly improves performance when modifying a trip and removes the freeze that was present after this operation.
> feat: Memo TripItem according to timeserie rev

- CHANGELOG.md
- src/components/EditDialogs/ModeEditDialog/ModeEditDialog.jsx
- src/components/EditDialogs/PurposeEditDialog/PurposeEditDialog.jsx
- src/components/Timeline/TimelineSections.jsx
- src/components/Trip/BottomSheet/BottomSheetContent.jsx
- src/components/Trip/BottomSheet/PurposeItem.jsx
- src/components/TripItem.jsx
- src/lib/timeseries.js
lorsqu'on avait un purpose en lowercase dans couch, l'affichage du purpose et 
de son icone était mal géré. On harmonise ici l'approche on utilisant le getter 
partout.
> fix purpose icon with lowercase purpose

- CHANGELOG.md
- manifest.webapp
- package.json
- src/constants.js
- src/doctypes/index.js
- src/lib/metrics.js
- src/lib/timeseries.js
- src/lib/timeseries.spec.js
- src/queries/queries.js
- src/targets/services/timeseriesWithoutAggregateMigration.js
- test/mockTrip.js
- yarn.lock
We now want to store an `aggregation` object in the
`io.cozy.timeseries.geojson` doctype, so it can be directly queried from
the app without having to retrieve the full geojson object, which can
very heavy, with most of the information being useless.
This service queries all the timeseries without the `aggregation` object
thanks to a partial filer and store the date of the last processed
timeserie, so it can be run incrementally.
> feat: Migrate timeseries without aggregation

- README.md
- manifest.webapp
- package.json
- src/components/TripsList.jsx
- src/constants.js
- src/doctypes/index.js
- src/lib/dacc.js
- src/lib/dacc.spec.js
- src/lib/exportTripsToCSV.js
- src/lib/services.js
- src/lib/timeseries.js
- src/lib/trips.js
- src/queries/queries.js
- src/queries/queries.spec.js
- src/targets/services/dacc.js
- src/targets/services/timeseriesWithoutAggregateMigration.js
- yarn.lock
This service will be launched every month. For each month, it will
aggregate the CO2 emitted by all the trips for this month, and the send
the result to the DACC.
Eventually, this will give the user the possibility to compare herself
with others contributors.
Note the service can only 12 contributions for each account for a single
execution, to prevent service timeout. If there are more months to
compute, the service relaunch itself.
> feat: Add service to send monthly CO2 emissions to DACC

- manifest.webapp
- package.json
- src/components/CO2EmissionsChart/CO2EmissionsChart.jsx
- src/components/CO2EmissionsChart/helpers.js
- src/components/CO2EmissionsChart/helpers.spec.js
- src/components/Views/Trips.jsx
- src/doctypes/index.js
- src/hooks/useFetchDACCAggregates.jsx
- src/hooks/useFetchDACCAggregates.spec.jsx
- src/lib/dacc.js
- src/lib/dacc.spec.js
- src/queries/queries.js
- src/targets/browser/setupApp.jsx
- yarn.lock
When the user consents to anonymously contribute to the CO2 global
emissions computations, the global average of all participating users
are displayed on the emissions chart, thanks to the DACC.
> feat: Display global user average CO2 emissions in chart

- src/components/CO2EmissionsChart/helpers.js
- src/locales/en.json
- src/locales/fr.json
petit souci de chevauchement de la color box dans le tooltip au clic sur une barre du graphique.
Quick fix qui consiste à la supprimer pour faire simple car : 
- Le tooltip n'est pas conforme aux specs
- pas de temps alloué à corriger ça
- pas d'autre solution convenable rapide
- le fait de cliquer sur les barres en mobile n'est pas une UX convenable (à terme l'idée étant de pouvoir cliquer sur la colonne et d'avoir un toolti plus personnalisé)
> Change wording in CO2EmissionsChart legend and color box

- CHANGELOG.md
- README.md
- package.json
- src/queries/queries.js
- yarn.lock
This is very useful to avoid querying full documents on the heavy aggregation 
request. Indeed, we require the timeseries for a whole year to build the
graph.
On a dataset of 926 timeseries, the query goes from 8.4 MB of data
retrieved in 2.35s, to 595 KB of data retrieved in 1.16s.
> feat: Use select on aggregation query

- CHANGELOG.md
- src/lib/dacc.js
- src/lib/dacc.spec.js
The user has to explicitely give consent to the DACC so the service can
be run
> feat: Do not send value to DACC if there is no consent

- package.json
- src/targets/services/timeseriesWithoutAggregateMigration.js
- yarn.lock
When an index with a partial filter was created and an other index
already existed with the same selector, it created a conflict and the
index with the partial filter wasn't created and the one without was
actually used. 
We met this situation for the migration service for an instance with an old index, which was stucked with
the first 1000 docs, because the query was returning all the docs, as the
partial index was not evaluated.
> Fix migration service for instances with old index

- src/queries/queries.js
query : buildOneYearOldTimeseriesWithAggregationByAccountId
> feat: Use partialIndex to get aggregation in graph query

- src/queries/queries.js
We have side-effects on instances already having an index on
`startDate` but without a partial index. In this situation, CouchDB will
fallback on this index, and won't apply the partial filter, leading to
unexpected results.
By the time we fix this issue in cozy-client, we use `endDate` as index
attribute.
> fix: Index on endDate rather than startDate

- src/queries/queries.js
This reverts commit 516c7fce33b5a5a12b72fba2ad7877117a9f0f6d.
This is because we discovered a bug with the usage of partial indexes
that should be fixed with https://github.com/cozy/cozy-client/pull/1193
In the meantime this is merged, let's disable the partial index
> fix: Revert partialIndex

- CHANGELOG.md
- README.md
- src/components/Trip/TripMap.jsx
This is an approximation. This would likely need to take into account the minimum height of the bottom sheet to be perfect, but it's not exposed by the component.
> fix: Vertically center the map on mobile when opening it

- package.json
- yarn.lock
Because of an issue in cozy-client, the limit wasn't properly
enforced and was causing errors in the app.
The buildAggregatedTimeseriesQueryByAccountId was retrieving data
without the required `endDate` because it was actually fetched by the
buildOneYearOldTimeseriesWithAggregationByAccountId query.
> fix: Invalid time value

- CHANGELOG.md
- src/components/Analysis/helpers.js
C'est pas normal de faire ça, ça fonctionne dans cozy-ui... solution temporaire ici.
voir l'issue : https://github.com/cozy/coachCO2/issues/166
> Remove square color in tooltip for PieChart

- CHANGELOG.md
- src/lib/helpers.js
Average speed used to be computed by the front-end, that was also in
charge to convert it from m/s to km/h. This is now computed by the
backend, and the front does not need to convert it anymore.
> fix: Do not convert average speed for display

- CHANGELOG.md
- src/components/Providers/TripProvider.jsx
- src/components/Providers/helpers.js
- src/components/Providers/helpers.spec.js
The sections array might be unordered, thus it is required to sort it by
date, so it is correctly displayed to the user.
> fix: Timeline order

- CHANGELOG.md
- README.md
- manifest.webapp
- package.json
- src/components/EditDialogs/PurposeEditDialog/PurposeEditDialog.jsx
- src/components/Trip/BottomSheet/BottomSheetContent.jsx
- src/components/Trip/BottomSheet/RecurringTripItem.jsx
- src/constants.js
- src/lib/dacc.js
- src/lib/exportTripsToCSV.js
- src/lib/recurringPurposes.js
- src/lib/recurringPurposes.spec.js
- src/lib/services.js
- src/lib/timeseries.js
- src/lib/timeseries.spec.js
- src/lib/trips.js
- src/lib/trips.spec.js
- src/locales/en.json
- src/locales/fr.json
- src/queries/queries.js
- src/targets/browser/index.jsx
- src/targets/browser/setupApp.jsx
- src/targets/services/dacc.js
- src/targets/services/recurringPurposes.js
- yarn.lock
This service is used to detect similar/recurring trips compared to a
trip with a manual purpose.
The detected recurring trips are then updated with this manual purpose
and are magically displayed in realtime to the user.
Note the recurring trips detection is very naïve for now: we simply
detect trips with the same (or reverse) start/end displayed place.
This is a first step and eventually will be improved later.
> Automatic purpose detection

- CHANGELOG.md
- src/queries/queries.js
This attribute is necessary to compute trip duration, which was
causing random crash of the app, probably because of concurrent queries
timing.
> fix: Add endDate in retrieved fields for trips query

- src/components/EditDialogs/PurposeEditDialog/PurposeEditDialog.jsx
- src/components/Trip/TripDialogDesktop.jsx
- src/components/Views/Trip.jsx
- src/lib/recurringPurposes.js
- src/lib/recurringPurposes.spec.js
- src/lib/timeseries.js
- src/lib/timeseries.spec.js
- src/locales/en.json
- src/locales/fr.json
- src/queries/queries.js
When the user wants to edit the purpose of a trip, a modal is now used
to know if the trip is recurring or not. If this is the case, the
recurring service is started. 
We take advantage of this to exclude explicit non-recurring trips from the automatic purpose detection.
> feat: Ask user for recurring trip 

- CHANGELOG.md
- manifest.webapp
Mistakenly added by https://github.com/cozy/coachCO2/commit/a6baf1d0e7c5df11cf2e19d71c537d57944fd44d probably because of the BC listed in https://github.com/cozy/cozy-ui/blob/master/CHANGELOG.md#breaking-changes-6 (but not relevant here as the `ContactsListModal` is not used
> fix: Remove useless permission

- manifest.webapp
- src/hooks/useExportTripsToCSV.jsx
- src/lib/recurringPurposes.js
- src/lib/recurringPurposes.spec.js
- src/queries/queries.js
- src/targets/services/recurringPurposes.js
When a connector imports trips, the service should be started, so newly
created trips might have an automatic purpose.
Note the behaviour is not the same depending on if the service is run
from the app or the trigger. In case of the app, we are looking for
similar existing trips to set them the new manual purpose. In case of a
trigger, we are searching for any trips without purpose and find similar
trips with manual purpose.
> feat: Start recurring service after trips creation

- src/constants.js
- src/lib/recurringPurposes.js
- src/lib/recurringPurposes.spec.js
- src/queries/queries.js
- src/queries/queries.spec.js
When looking for similar trips to find recurring trips, we were only
looking on the start/end place name.
We now add a distance metric that consists of searching only for trips
with a total distance close enough to the reference trip.
> feat: Add distance metric for trips similarity detection

- CHANGELOG.md
- src/components/Analysis/Modes/LoadedModesList.jsx
- src/components/Analysis/Modes/LoadedModesList.spec.js
- src/components/Analysis/Purposes/LoadedPurposesList.jsx
- src/components/Analysis/Purposes/LoadedPurposesList.spec.js
- src/components/AppRouteur.jsx
- src/components/Trip/TripDialogMobile.jsx
- src/components/TripItem.jsx
- src/components/TripsList.jsx
- src/components/Views/ModeAnalysis.jsx
- src/components/Views/PurposeAnalysis.jsx
Change le comportement du back dans la toolbar/cozybar en haut. Au lieu de faire un simple back browser (ce qui pose souci par exemple lors d'un point d'entrée direct, ou dans l'AA) on utilise des routes spécifiques.
Pour afficher un trajet, on utilisait avant la même route qu'on vienne de la home ou des l'analyse. On utilise maintenant 2 routes différentes.
je n'ai pas de temps alloué au projet, c'est un correctif rapide, initialement c'est pour pouvoir afficher des modales avec des routes par dessus une autre route, sur desktop...
> Adds some route and goBack improvements

- CHANGELOG.md
- src/lib/recurringPurposes.js
- src/lib/recurringPurposes.spec.js
We discovered that the `aggregation.endPlaceDisplayName` might be
missing in some cases.
So, rather throwing an error when a required attribute is missing, we
log an error and continue the service execution.
> fix: Do not throw an error when timeserie is malformed

- src/components/EditDialogs/RecurrenceEditDialog/RecurrenceEditDialogTitle.jsx
This makes the bottom sheet closer to the mock-up.
> Improve margins in the recurrence edit dialog title on mobile

- CHANGELOG.md
- src/components/Analysis/Modes/LoadedModesList.jsx
- src/components/Analysis/Modes/LoadedModesList.spec.js
- src/components/Analysis/Purposes/LoadedPurposesList.jsx
- src/components/Analysis/Purposes/LoadedPurposesList.spec.js
- src/components/App.jsx
- src/components/AppRouter.jsx
- src/components/AppRouteur.jsx
- src/components/Trip/TripDialogDesktop.jsx
- src/components/Trip/TripDialogDesktopContent.jsx
- src/components/Trip/TripDialogMobile.jsx
- src/components/TripItem.jsx
- src/components/TripsList.jsx
- src/components/Views/Trip.jsx
L'idée ici est de pouvoir afficher une modale avec une certaine route, par-dessus l'application "sans perdre de vue" la route sur laquelle on était avant d'ouvrir la modale. Ainsi on peut revenir sur la route initiale sans faire de rechargement de composant, et donc par exemple garder sa position si jamais on a scrollé dans le contenu. Cela permet aussi, puisqu'on a des routes spécifiques par modale, d'ouvrir l'application directement sur une route avec modale ouverte, ou faire un hard refresh sans perdre l'ouverture de la modale.
Pour se faire une modification du router a été nécessaire :
- utilisation d'un `background` qu'on passe à la place du `location` sur `Routes` principal : `<Routes location={background || location}>`
- utilisation d'un deuxième `Routes` afin de gérer l'ajout des …
> Router rework

- src/components/AppProviders.jsx
- src/components/AppRouter.jsx
- src/components/Views/ModeAnalysis.jsx
- src/components/Views/PurposeAnalysis.jsx
- src/targets/browser/index.jsx
Ceci est une régression dû à l'implémentation des nouvelles routes. Sur la page d'analyse, si on change la date dans le sélecteur, et qu'on navigue ensuite sur la liste des modes/purposes, la date se réinitialisait au dernier mois.
C'était dû au rerender du provider de date (qui set la date à `null` par défaut) à cause visiblement du fait qu'il faut utiliser 
`Outlet` dans la route parente.
> Selected date changes to last month when selecting a  mode/purpose in analysis

- app.config.babel-loader-leaflet.js
- app.config.js
- package.json
- src/components/Trip/TripMap.jsx
- src/components/Trip/TripMapContent.jsx
- src/targets/browser/index.jsx
- src/targets/browser/setupApp.jsx
- src/utils/bar.js
- yarn.lock
Mise à jour de l'app en React 18.
La mise à jour de react-leaflet en v4+ était requise.
J'en ai profité pour mettre à jour les libs `@testing-library/*`
```
* Update react-leaflet from [2.8.0](https://github.com/PaulLeCam/react-leaflet/releases/tag/v2.8.0) to [4.1.0](https://github.com/PaulLeCam/react-leaflet/releases/tag/v4.1.0)
* Update leaflet from [1.7.1](https://github.com/Leaflet/Leaflet/releases/tag/v1.7.1) to [1.9.1](https://github.com/Leaflet/Leaflet/releases/tag/v1.9.1)
* Update react packages from [17.0.2](https://github.com/facebook/react/releases/tag/v17.0.2) to [18.2.0](https://github.com/facebook/react/releases/tag/v18.2.0)
* Update @testing-library/react from [11.2.7](https://github.com/testing-library/react-testing-library/releases/tag/v11.2.7) to …
```
> Upgrade to react 18

- package.json
- yarn.lock
* Fix `unusable index`. For few instances, a 'Unusable index' error is thrown, because of a problematic index migration, that should be automatically fixed by cozy-client since the [31.1.1](https://github.com/cozy/cozy-client/releases/tag/v33.1.1)
> fix: Unusable index on some instances

- src/components/CO2EmissionDaccAlertSwitcher.jsx
- src/components/CO2EmissionDaccSwitcher.jsx
- src/components/CO2EmissionsChart/CO2EmissionsChart.jsx
- src/components/DaccManager/DaccManager.jsx
- src/components/DaccManager/DaccManager.spec.js
- src/components/Goals/BikeGoal/BikeGoalAlertManager.jsx
- src/components/Goals/BikeGoal/BikeGoalAlertSwitcher.jsx
- src/components/Goals/BikeGoal/BikeGoalAlertSwitcher.spec.jsx
- src/components/Goals/BikeGoal/BikeGoalOnboardedSwitcher.jsx
- src/components/Goals/BikeGoal/BikeGoalSwitcher.jsx
- src/components/Views/Settings.jsx
- src/hooks/useSettings.jsx
- src/hooks/useSettings.spec.jsx
- src/lib/dacc.js
- src/lib/dacc.spec.js
- src/locales/en.json
- src/locales/fr.json
This PR mainly focuses on two things: changing the shape of the app settings in the database, which is a breaking change (no migration path is planned), and add one switch to open the onboarding if not completed yet, or to deactivate the bike goal feature afterwards.
The switch is kept behind the flag `coachco2.bikegoal.enabled` while the breaking change applies to every user of this branch.
Another switch is also added in admin mode to help to reset the upcoming onboarding.
```
* Move CO2 Emission settings to a dedicated object
* Add a switch to open the onboarding or disable the bike goal
```
> Add a switch to open the onboarding or disable the bike goal

- src/components/Goals/BikeGoal/BikeGoalAlertManager.jsx
- src/components/Views/BikeGoalOnboarding.jsx
- src/locales/en.json
- src/locales/fr.json
This makes it so:
- clicking on the "Participate" button in the alerter opens the onboarding
- clicking on the back button in the onboarding goes back to the background location (either the settings or the trips)
- clicking on a temporary "Finish" button in the onboarding opens the current year for the bike goal
This also updates the title of the onboarding dialog.
```
* Add navigation to and from the onboarding page
```
> Add navigation to and from the onboarding page

- src/components/Views/BikeGoalOnboarding.jsx
This is on top of #220.
This hides the alerter and enables the bike goal feature when clicking on the temporary "Finish" button in the onboarding.
At this point of the stepper, most of the settings related to the feature should already be set, so there is no need to set them again (please note that the stepper is not yet implemented, so that's not the case currently).
```
* Enabled the bike goal feature and disable the onboarding once completed
```
> Enabled the bike goal feature and disable the onboarding once completed

- app.config.js
With this configuration we can use `.styl` files.
```
* Add css-modules config from cozy-script
```
> chore: Add css-modules config from cozy-script

- src/components/DaccBanner/CO2EmissionDaccBanner.jsx
- src/components/DaccManager/BikeGoalDaccManager.jsx
- src/components/DaccManager/CO2EmissionDaccCompareDialog.jsx
- src/components/DaccManager/CO2EmissionDaccManager.jsx
- src/components/DaccManager/CO2EmissionDaccManager.spec.js
- src/components/DaccManager/DaccManager.jsx
- src/components/DaccManager/DaccPermissionsDialog.jsx
- src/components/DaccManager/DaccReasonsDialog.jsx
- src/components/Views/Trips.jsx
- src/locales/en.json
- src/locales/fr.json
Mostly renaming and refactoring to extract the blue permission modal from the CO2 emission Dacc manager to reuse it for the bike goal feature. The only variable part is the type of data we ask to share.
The `BikeGoalDaccManager` component introduced here is not used anywhere yet but it will be in the stepper on the onboarding page. This component does not really carry any logic and just takes callbacks as props that will be called by the stepper, contrary to the similar component `CO2EmissionDaccManager`.
```
* Make the permission dialog reusable
```
> Make the permission dialog reusable

- package.json
- yarn.lock
Suite à ce commit https://github.com/cozy/create-cozy-app/commit/fa07a25 (dans la version 6.3.1)
Et en attendant un fix de ce dernier
```
* Revert `cozy-scripts` to 6.3.0 for prevent duplicate css.
```
> feat: Revert cozy-scripts to 6.3.0 for prevent duplicate css

- src/components/Goals/BikeGoal/BikeGoalManager.jsx
Initially, there is no `bikeGoal` object in the settings document, so this made the app crash.
(changelog omitted)
> Fix `BikeGoalManager` component when `bikeGoal` is not defined

- src/components/Goals/BikeGoal/helpers.js
- src/components/Goals/BikeGoal/helpers.spec.js
- src/lib/timeseries.js
- src/lib/timeseries.spec.js
On ne comptait pas correctement le nombre de jour de l'objectif vélo.
On ne se base maintenant que sur le startDate d'un timeserie, on compte alors le nombre de jour pour lesquels il y a au moins un timeserie avec un startDate. En revanche : 
- s'il y a plusieurs timerserie pour un même jour, on n'en compte qu'un seul
- si un timerserie commence le lendemain moins de 12 heures plus tard qu'un timerserie de la veille, on ne le compte pas
> fix(BikeGoal): Helper to count days of bike goal was not correct

- package.json
- src/components/Goals/BikeGoal/Edit/EditModalContent.jsx
- src/components/Goals/BikeGoal/Edit/ModificationModalContent.jsx
- src/components/Goals/BikeGoal/Edit/PercentageField.jsx
- src/components/Goals/BikeGoal/Edit/helpers.js
- src/components/Goals/BikeGoal/Edit/helpers.spec.js
- src/components/Goals/BikeGoal/helpers.js
- src/components/Views/BikeGoalOnboarding.jsx
- src/components/Views/BikeGoalOnboardingSteps/BikeGoalOnboardingComparison.jsx
- src/components/Views/BikeGoalOnboardingSteps/BikeGoalOnboardingConclusion.jsx
- src/components/Views/BikeGoalOnboardingSteps/BikeGoalOnboardingDetection.jsx
- src/components/Views/BikeGoalOnboardingSteps/BikeGoalOnboardingIntroduction.jsx
- src/components/Views/BikeGoalOnboardingSteps/BikeGoalOnboardingNaming.jsx
- src/components/Views/BikeGoalOnboardingSteps/BikeGoalOnboardingTiming.jsx
- src/locales/en.json
- src/locales/fr.json
- yarn.lock
This adds the onboarding stepper that can be opened from the blue alerter or from the settings.
Please note that the stepper is not fully compliant with the specs and will soon or later need Cozy UI to be updated with cozy/cozy-ui#2280 included.
```
* Add the onboarding for the bike goal feature
* Allow to customize the source identity via a flag
```
> Add bike goal onboarding stepper

- package.json
- src/components/Goals/BikeGoal/BikeGoalActions.jsx
- src/components/Goals/BikeGoal/BikeGoalDialogMobile.jsx
- src/lib/timeseries.js
- src/lib/timeseries.spec.js
- yarn.lock
Les boutons d'actions sur mobile étaient aboluste en haut à droite, donc le contenu passait en-dessous, ce qui ne convenait pas.
On corrige également un mutate sur l'ordre de tri de la liste :facepalm:
Pas de changelog on n'apporte pas de différence par rapport à la version précédente de l'app
> BikeGoal: fix actions position in mobile and list order

- src/locales/en.json
- src/locales/fr.json
So it can be customized. This has the downside to not be localizable.
(changelog omitted)
> Make "of" part of the source identity

- CHANGELOG.md
- manifest.webapp
- package.json
- src/lib/dacc.js
This is basically a backport of a fix that was in 365a34b82f19e035b58449eb1ee2d6de358fc6ea.
```
* Prevent dacc service from crashing when there is no settings document
```
> Prevent dacc service from crashing when there is no settings document

- src/components/Trip/TripMapContent.jsx
The import without a variable of the style sheet no longer works.
I don't have the precise reason, but it's recommended to do named imports.
```
* Style of pointToLayer on Trip Map
```
> fix: Style of pointToLayer on Trip Map

- src/components/Goals/BikeGoal/BikeGoalAchievement.jsx
- src/components/Goals/BikeGoal/BikeGoalChart.jsx
- src/components/Goals/BikeGoal/BikeGoalDaccSwitcher.jsx
- src/components/Goals/BikeGoal/BikeGoalDialogMobile.jsx
- src/components/Goals/BikeGoal/BikeGoalSummary.jsx
- src/components/Goals/BikeGoal/BikeGoalSummaryDaccItems.jsx
- src/components/Goals/BikeGoal/BikeGoalSummaryItem.jsx
- src/components/Goals/BikeGoal/BikeGoalSummaryYearlyItem.jsx
- src/components/Goals/BikeGoal/BikeGoalViewDesktop.jsx
- src/components/Goals/BikeGoal/helpers.js
- src/components/Views/BikeGoal.jsx
- src/components/Views/Settings.jsx
- src/locales/en.json
- src/locales/fr.json
Lorsque le DACC est activé pour l'objectif vélo, au même titre que pour les émissions CO², on affiche maintenant les valeurs du DACC dans les grapiques et cartouche d'information.
note: la partie récupération des datas du DACC ne sont pas encore en place, un mock est utilisé. A savoir que toute la feature FMD (bike goal) est derrière un flag
```
* Add bike goal dacc switcher for admin mode
* Use SendToDACC bike goal option to show proper info and charts
```
> Use SendToDACC bike goal option to show proper info

- src/components/helpers.js
- src/components/helpers.spec.js
- src/constants.js
- src/lib/metrics.js
- src/lib/timeseries.spec.js
- src/lib/trips.js
- src/lib/trips.spec.js
In some cases, it happens that openpath computes a Depending on the motion detection, openpath has a different set of modes:
https://github.com/e-mission/e-mission-server/blob/gis-based-mode-detection/emission/core/wrapper/motionactivity.py#L12 vs
https://github.com/e-mission/e-mission-server/blob/gis-based-mode-detection/emission/core/wrapper/modeprediction.py#L17
The fist one was not supported, causing unexpected unknown modes.
```
*
* Handle all modes coming from openpath
*
```
> fix: Handle all modes from openpath

- src/components/Goals/BikeGoal/Edit/ModificationModalContent.jsx
```
* On SMP edit, do not use the ellipsis to see the entire group name
```
> feat: On SMP edit, do not use the ellipsis to see the entire group name

- src/locales/en.json
- src/locales/fr.json
When asking to save a start/end place, we only displayed "Contact" to the user, which can be misleading.
> feat: Improve wording

- scripts/remove-purposes.js
- src/constants.js
- src/lib/dacc.spec.js
- src/lib/exportTripsToCSV.spec.js
- src/lib/recurringPurposes.js
- src/lib/recurringPurposes.spec.js
- src/lib/timeseries.js
- src/lib/timeseries.spec.js
When trying to find recurring timeseries with same purpose, 
we rely on the coordinates, as we consider that trips with
same start / end points have quite often the same purpose.
However, when the start / end points are the same, this assumption seems less relevant: typically trips from and to the home address can have multiple purposes.
That is why we introduce a special case for "loop trip":  we filter out trips with a too high difference in distance  to only set  same purposes to roughly-same-distance loop trips.
This is obviously not perfect, and should probably be eventually improved, but might be a good enough quick win for now.
```
* Filter recurring loop trips on distance
*
*
```
> feat: Filter recurring loop trips on distance

- manifest.webapp
- src/components/ContactToPlace/ContactToPlaceDialogActions.jsx
- src/components/ContactToPlace/helpers.js
- src/components/EditDialogs/ModeEditDialog/ModeEditDialog.jsx
- src/components/EditDialogs/ModeEditDialog/helpers.js
- src/components/Trip/TripDialog.jsx
- src/components/TripItem.jsx
- src/lib/recurringPurposes.js
- src/lib/services.js
- src/lib/timeseries.js
- src/lib/timeseries.spec.js
- src/queries/queries.js
- src/targets/services/recurringPurposes.js
- src/targets/services/timeseriesWithoutAggregateMigration.js
On souhaite créer un titre au déplacement selon les noms des points de départ et d'arrivée des déplacements
voir issue https://github.com/cozy/coachCO2/issues/296 et question que cela a généré.
Info au reviewers : nous n'avons plus tellement le temps de changer l'approche...
```
* Automatic creation of trip titles
```
> Automatic generation of trip titles

- src/components/ContactToPlace/ContactToPlaceDialogActions.jsx
- src/components/ContactToPlace/helpers.js
see https://github.com/cozy/cozy-client/issues/1403
> fix: Trip title wasn't showing correct wording

- src/lib/recurringPurposes.js
- src/lib/recurringPurposes.spec.js
- src/lib/timeseries.js
The recurrence service is able to detect when a trip start or end should
be associated with a contact's address, because of their coordinates.
However, this was not correctly working, because the
`makeAggregationTitle` was expecting hydrated timeseries, i.e. including
complete contacts in their docs.
ATM this must be done manually in node.
```
* 
* Get correct title when contacts are automatically associated to trips
*
```
> fix: Get correct title when contacts are associated to trips

- package.json
- src/locales/en.json
- src/locales/fr.json
- yarn.lock
We got rejected by Play Store because both AllowLocationDialog and LocationRefusedDialog did not contains required wordings
Based on google documentation, those dialogs must:
- Indicate how location is used in the background by including one of these phrases: “background” / “when the app is closed” / “always in use” / “when the app is not in use”.
- Include a list of all the features that use location in the background.
Related PR: https://github.com/cozy/cozy-ui/pull/2519
```
*
* Edit Location request dialogs to fit Play Store requirements
*
```
> fix: Edit Location request dialogs to fit Play Store requirements

- scripts/remove-purposes.js
- src/components/Providers/ContactToPlaceProvider.jsx
When creating a new contact, a Cozy Contact service is triggered with a
5 sec debounce. This service updates the contact and create a new _rev,
which can cause conflicts. And when conflicts arise, the contact is
never actually linked to the trip in database, making the feature
pointless. Even worse, the user was never informed about it, the error
being silent.
Fortunately, the Cozy realtime is there to dynamically updates the contact
with the new data.
Unfortunately, this was not properly handled: the contact itself was
never queried, and, once queried, never set in the state.
The conflicts should now be avoided, making the world a better place.
And for even more peace, see: https://github.com/cozy/cozy-client/issues/1414
```
* 
* Fix failed trip association with contact addresses  
* Add …
```
> Fix contact creation

- src/components/Goals/BikeGoal/helpers.js
- src/components/Goals/BikeGoal/helpers.spec.js
```
* The `getDaysToReach` function could be called with its `settings` parameter undefined, when it should not.
In this case it used the flag value.
The visible fix of this commit is the `BikeGoalChart` which could be rendered more than 100%,  and caused a graphics bug.
```
> fix: Add missing param to countDaysOrDaysToReach function

- src/components/GeolocationTracking/helpers.js
isGeolocationTrackingPossible was, after a fresh flagship app install, returing null because flags were not set yet.
Transforming it to a function solve the issue.
> fix: isGeolocationTrackingPossible returned null after a fresh flagship app install

- src/components/EmptyContent/EmptyContentManager.jsx
- src/components/GeolocationTracking/helpers.js
- src/components/Providers/GeolocationTrackingProvider.jsx
On coachco2 loading, we can see page switching very quickly between InstallApp and Welcome page because by default we displayed InstallApp page, and after a request to the flagship app we decided to stay on this page or change to Welcome page.
Now we wait to be sure of the value of isGeolocationTrackingAvailable and isGeolocationTrackingEnabled before displaying something.
> fix: Avoid blinking page on load

- src/components/CO2EmissionsChart/CO2EmissionsChart.jsx
- src/components/Goals/BikeGoal/BikeGoalChart.jsx
- src/components/Goals/BikeGoal/BikeGoalSummaryDaccItems.jsx
- src/components/Goals/BikeGoal/BikeGoalSummaryItem.jsx
- src/components/Goals/BikeGoal/helpers.js
- src/hooks/useFetchDACCAggregates.jsx
- src/hooks/useFetchDACCAggregates.spec.jsx
- src/lib/daccBikeGoal.js
- src/lib/daccBikeGoal.spec.js
Users can visualize the average bike goal status for their own group and compare themselves
> feat: Query DACC to get avg bike goal days

- src/components/CO2EmissionsChart/CO2EmissionsChart.jsx
Since we render the CO2EmissionsChart only when we have an account & a timeseries, we are sur to display it when we render it.
So this is a quick fix to avoid visual glitch by reserving the 190px height.
The right solution should be to display an empty graph, but I didn't have the time to check how to do that.
```
*
*
*
```
> fix: Reserve the height for the graph

- src/components/SelectDatesWrapper.jsx
Since we can't not make the query when there is no account, we should set the data loading to false.
Next commit will be to not render this component if there is no account in order to make it easier to understand and to simplify the code.
> fix: setIsloadingDate to false when no account

- src/components/EditDialogs/PurposeEditDialog/helpers.js
- src/components/Timeline/TimelineNode.jsx
- src/locales/en.json
- src/locales/fr.json
On active le fait de pouvoir cliquer sur un point de départ/arrivée afin d'y assigner un contact à tous les déplacements, quelque soit leur motif (réservé avant au seul motif domicile/travail)
Initialement on avait préféré mettre ces changement derrière un flag car une MEP est prévu aujourd'hui, mais on a tester la feature en live et il a été décidé de passer cette modification avant la MEP.
> Activate ContactToPlace feature for every  purposes

- .travis.yml
- package.json
- yarn.lock
```
* Update `cozy-scripts` from `8.1.2` to `8.2.0`
* Update travis config, keep tests in node 16 and node 20 because currently services are executed with node 16.
```
> chore: Update travis configuration

- .travis.yml
```
* Travis executes the yarn test command by default when we specify multiple node versions at the root.
In this case we run the tests twice.
```
> chore: Refactor Travis CI stages

- src/components/CO2EmissionDaccAlertSwitcher.jsx
- src/components/CO2EmissionDaccSwitcher.jsx
- src/components/Goals/BikeGoal/BikeGoalAlertSuccessSwitcher.jsx
- src/components/Goals/BikeGoal/BikeGoalAlertSwitcher.jsx
- src/components/Goals/BikeGoal/BikeGoalDaccSwitcher.jsx
- src/components/Goals/BikeGoal/BikeGoalOnboardedSwitcher.jsx
- src/components/Goals/BikeGoal/BikeGoalSwitcher.jsx
The `edge="end"` prop adds a negative margin (-8px) which in this case creates a horizontal offset.
> fix: Remove horizontal scroll on Settings page

- src/components/GeolocationTracking/helpers.js
- src/components/GeolocationTracking/helpers.spec.js
On first enabling geolocation tracking, the toggle is not set as on because there is a bug in cozy-flagship-app. `await setGeolocationTracking(true)`  return BEFORE the tracking is enabled. The fix has been done in cozy-flagship-app
(bae397dd9060bb6122bfcdd2a1dab4e5cbb53687) but we need to wait for the next release. So we fix it now for the moment by always considering it as a success. It should be safe because starting tracking should not fail.
```
* Show toggle as on after first enabling geolocation tracking
```
> fix: Show toggle as on after first enabling geolocation tracking

- src/constants.js
- src/lib/daccCentreValDeLoireExpe.js
This is useful to measure how many users gave their explicit consent to participate to the experimentation.
```
* Add new DACC measure for consent 
*
*
```
> [DAT-25] feat: Add DACC mesure for consent

- src/components/Providers/GeolocationTrackingProvider.jsx
- src/hooks/useVisibilityChange.js
With the recent add of geolocation quota check on flagship side, the geolocation tracking can be disabled when the flagship app (with coachco2 opened) is in background. When the user will come back to the flagship app, the geolocation tracking will be disabled, but the geolocation tracking toggle on coachco2 will be enabled.
Here we solve the issue by syncing the geolocation tracking status when coachco2 becomes visible.
```
* Show correct geolocation tracking status if geolocation tracking has been disabled in background because of quota exceeded
```
> fix: Sync geolocation tracking status on visibility change

- manifest.webapp
- src/lib/openpath/queries.js
- src/queries/queries.js
- src/targets/services/fetchOpenPathTrips.js
This is useful to be able to request the service directly from a webhook, typically called from an openpath server.
Related to https://github.com/cozy/cozy-flagship-app/pull/1133
```
* Allow triggering fetchOpenPathTripsByWebhook service from webhook
*
*
```
> [DAT-26]  feat: Add webhook trigger for fetchOpenPathTrips service

- manifest.webapp
- src/constants.js
- src/lib/daccCentreValDeLoireExpe.js
- src/lib/daccCentreValDeLoireExpe.spec.js
:warning:  Relies on https://github.com/cozy/coachCO2/pull/370 that must be merged first
- Rename previous trips-* measures into sections-* measures
- Add new trips-* measures for actual trips
```
* Add new trips measures
* Rename sections measures
*
*
```
> [DAT-27] feat: Add new DACC measures for trips

- README.md
- scripts/save-random-trip.js
- src/components/SelectDates/helpers.js
Dans le cas où il n'y a que des trajets sur une même année, les booléens `isSelectedYearSameAsEarliestYear` & `isSelectedYearSameAsLatestYear` sont vrais.
Dans ce cas précis, nous souhaitons garder les premiers mois de l'année, jusqu'au mois du dernier trajet.
```
* Month selector on the trips Analytics page
* Generate trip with custom date
```
> Fix: Month selector on the trips Analytics page

- src/components/SelectDates/SelectDates.jsx
Navigation with arrows should not display months without trips.
```
* On Analysis pages, navigation with arrows should not display months without trips.
```
> fix: Filter arrows on Analysis pages

- src/lib/timeseries.js
- src/lib/timeseries.spec.js
- src/lib/types.js
We noticed that sometimes, sections values have integrity issues, as returned by openpath.
When we detect negative values, we recompute the whole section values for distance, duration  and speed.
```
*
* Fix negative values in trips section
*
```
> [DAT-29] fix: Handle negative values

- src/components/SelectDates/SelectDates.jsx
- src/components/SelectDates/helpers.js
- src/components/SelectDates/helpers.spec.js
Added a log if no date is found, because that shouldn't happen.
> fix: The arrow filter must ignore multiple occurrences of the same month

- README.md
- scripts/accounts-fixtures.js
- scripts/save-account.js
```
* For `openpath` account you can specify a custom token. Specify a token set the `--source-account` option to `openpath`
```
> chore: Add token for openpath account

- src/lib/openpath/lib.js
- src/lib/openpath/lib.spec.js
- src/lib/openpath/normalizeData.js
- src/lib/openpath/openpath.js
- src/lib/openpath/queries.js
- src/lib/openpath/save.js
- src/lib/types.js
- src/targets/services/timeseriesWithoutAggregateMigration.js
We used to rely on the `timeseriesWithoutAggregation` service in order to compute the `aggregation` block. This service is run after a geojson creation, with 1min debounce.
This is not ideal because it is an async operation, which mean that some timeseries can exist without the `aggregation`, forcing the app to adapt queries and checks to guarantee its existence.
As the trips are now fetched through a coachco2 service (and not from an external konnector), we can now compute this `aggregation` before saving the trips.
This users will see their trips faster (better UX), and eventually we won't have to check for this block existence anymore (better DX).
```
* Normalize trips as soon as they are fetched
*
*
```
> [DAT-18] feat: Compute geojson aggregation in fetch service

- src/targets/browser/setupApp.jsx
By default `InboundFilters` is enabled and ignore
errors that start with Script error or
Javascript error: Script error.
https://docs.sentry.io/platforms/javascript/guides/react/configuration/integrations/inboundfilters/
So there were no errors in Sentry. I disable all
the `defaultIntegrations` in order to not have any filter.
I saw this, by adding `debug:true` to the Sentry
config object, so I had message like
"Event droped due to being matched by ignoreErrors options"
```
* Errors are now sent to sentry
```
I know that I removed the ignore stuff that we had before, but we need to get errors on sentry ASAP. I didn't have the time to fine tune it yet.
> fix: Sentry issue

- src/queries/queries.js
This query should not sort the accounts, because since there is a limitBy, we can run into a case where we don't see all the latest trips.
The presence in the .select is not necessary either.
> fix: Querying all trips from all accounts

- src/lib/trips.js
- src/lib/trips.spec.js
In a past commit we removed the condition on manual mode in the `getFeatureMode` function. (see c2c2ad0)
Today we need this condition because `getFeatureMode` is also used by the Export function.
Without this condition, the latter exports the trips without looking at the changes made by the user in the meantime.
```
* The export must also have the modes chosen manually
```
> fix: The export must also have the modes chosen manually

- src/constants.js
- src/lib/openpath/lib.js
- src/lib/openpath/lib.spec.js
- src/lib/openpath/normalizeData.js
- src/lib/openpath/openpath.js
- src/lib/openpath/openpath.spec.js
- src/lib/openpath/save.js
- src/lib/openpath/traceRequests.js
- src/lib/openpath/utils.js
- src/lib/openpath/utils.spec.js
- src/targets/services/fetchOpenPathTrips.js
When the fetch service has saved new trips, request the openpath server
to purge itself from old data.
This is useful to prevent out-of-control database growing, and improve
pipeline performances, as we measured a performance drop when the
`Stage_analysis_timeseries` grows.
Note this purge is called only when new trips are saved, and is desgined
to keep a 7-days security before purging.
```
* Request openpath purge after new saved trips
* Trip deduplication
* Fetch service auto-restart when timeout is coming 
*
```
> [DAT-10] feat: Request openpath purge after fetch 

- src/lib/geolocationQuota/lib.js
- src/queries/queries.js
Fix of https://github.com/cozy/coachCO2/pull/388
> fix: Use startDate sorted by asc for geolocation quota notification

- src/components/GeolocationTracking/helpers.js
- src/components/Providers/GeolocationTrackingProvider.jsx
getGeolocationTrackingId method was used to copy openpath identifier (a button hidden behind a flag). But it was not implemented so it was failing silently.
```
* "Copy OpenPath identifier" debug button return correctly OpenPath identifier
```
> "Copy OpenPath identifier" debug button return correctly OpenPath identifier

- src/components/GeolocationTracking/helpers.js
By default, the openpath login account is the device name, as provided by the OS, e.g. "iPhone"
However, this login can include additional formatting, such as "iPhone - Created on 01/01/24".
Thus, to determine if a new openpath account should be created, we should rely on the deterministic OS device name rather than the login.
```
*
* Rely on device name rather than login for account creation
*
```
> [DAT-35] fix: Rely on device name rather than login

- src/components/GeolocationTracking/helpers.js
- src/lib/openpath/openpath.js
- src/lib/openpath/queries.js
- src/queries/queries.js
- src/targets/services/fetchOpenPathTrips.js
It can happen that a user has several openpath service accounts, typically because of https://github.com/cozy/coachCO2/pull/405, or if he changed the device.
To be sure we are not missing any trip, we now query all the openpath accounts.
```
*
* Handle multiple service accounts, to ensure all trips retrieval
*
```
> [VER-224] fix: Handle multiple service accounts

- src/components/EditDialogs/PurposeEditDialog/helpers.js
With the exception of `commute`, all others (except Unknown purpose) should only show the modal if no POI already exists.
```
* All purposes must offer the POI modal
```
> feat: All purposes must offer the POI modal

- src/components/ContactToPlace/ContactToPlaceDialogActions.jsx
- src/components/ContactToPlace/helpers.js
- src/components/EditDialogs/PurposeEditDialog/PurposeEditDialog.jsx
- src/components/EditDialogs/PurposeEditDialog/helpers.js
For all changes of purpose, except "Going to or from work", it should only appear if no POI has ever been saved.
As soon as a POI is created, the POI modal should never be displayed again. (except for "Going to or from work" purpose)
Cette PR corrige une mauvaise interprétation du besoin fait ici : https://github.com/cozy/coachCO2/pull/408
> feat: Behavior of POI modal

- src/targets/browser/index.jsx
- src/targets/browser/setupApp.jsx
For a long time we have had problems with the app's routes opening modals.
Indeed, in dev we could not refresh the app with an open modal without it being duplicated.
It is the fact of having the `createRoot` function in the `init` function of the app that causes these problems, because the latter executes twice when the app is launched via the `yarn start/watch` commands.
Other Cozy apps (in the same versions of React) execute this function in `setupApp` which is memoized, and thus avoids the double execution of `createRoot`.
```
* Fix duplication of `createRoot` when reloading
```
> chore: Fix duplication of `createRoot` when reloading

- src/lib/openpath/lib.js
- src/lib/openpath/traceRequests.js
Sometimes, the openpath server returns a 500 error on retrieval trip API, when there is a particular trip that is malformed.
To avoid being blocked by this, we catch the 500 error and continue the execution: https://github.com/cozy/coachCO2/blob/master/src/lib/openpath/lib.js#L92
However, this was not properly working because of a wrong error catching
```
*
* Correctly handle 500 errors when fetching trips
*
```
> [DAT-42] Fix 500 openpath

- manifest.webapp
- src/components/AccountSelector.jsx
- src/components/AppProviders.jsx
- src/components/CO2EmissionsChart/CO2EmissionsChart.jsx
- src/components/EmptyContent/ChangeAccount.jsx
- src/components/EmptyContent/EmptyContentManager.jsx
- src/components/EmptyContent/EmptyContentManager.spec.jsx
- src/components/EmptyContent/GPSStandby.jsx
- src/components/EmptyContent/helpers.js
- src/components/EmptyContent/helpers.spec.js
- src/components/Goals/BikeGoal/BikeGoalManager.jsx
- src/components/Goals/BikeGoal/BikeGoalSummary.jsx
- src/components/ListWrapper.jsx
- src/components/Providers/AccountProvider.jsx
- src/components/SelectDatesWrapper.jsx
- src/components/Views/BikeGoal.jsx
- src/components/Views/Settings.jsx
- src/components/Views/Trips.jsx
- src/hooks/useExportTripsToCSV.jsx
- src/hooks/useExportTripsToCSV.spec.jsx
- src/lib/computeAggregateService.js
- src/queries/nodeQueries.js
- src/queries/queries.js
- src/queries/queries.spec.js
- src/targets/browser/setupApp.jsx
- src/targets/services/computeAggregate.js
Cette PR corrige la disparition des sources dans le sélecteur sur la page des paramètres de l'application.
En effet, dans le cas où un connecteur est déconnecté ou désinstallé, la source qui n'est autre que le compte(`io.cozy.accounts`) est supprimé.
En sachant cela, et comme nous souhaitons pouvoir continuer à sélectionner les noms des comptes avec leur trajets, nous devons plutôt nous servir de la propriété `captureDevice` présente sur tous les `timeseries` qui ont pour valeur le nom du compte d'où elles proviennent.
Ainsi, nous pouvons continuer à sélectionner le nom des comptes et afficher leurs trajets.
Le service ne réagissant qu'à la création d'un `timeseries`, nous avons besoin de créer un Job et de le déclencher une fois "manuellement" lorsque l'utilisateur arrive sur l'app. …
> Feat: The disappearance of sources

- src/lib/services.js
Services could crash if user has a locale that is not supported by services. Currently, only "en" and "fr" are supported.
```
* Services will not crash anymore when trying to translate in an unsupported locale
```
> fix: initPolyglot should load the "en" as a fallback

- src/queries/queries.js
...must return referenced contacts.
```
* Each time the recurrence service was run on a trip with defined contacts, the related contacts were not found.
The title of the modal then returned to its default value (the place of arrival)
```
> fix: The query  used by `recurringPurposes` service

- src/components/ContactToPlace/CustomLabelDialog.jsx
- src/components/ContactToPlace/LabelItem.jsx
- src/components/ContactToPlace/actions/customLabel.jsx
- src/components/ContactToPlace/actions/helpers.js
- src/components/ContactToPlace/actions/helpers.spec.js
- src/components/ContactToPlace/actions/home.jsx
- src/components/ContactToPlace/actions/noLabel.jsx
- src/components/ContactToPlace/actions/work.jsx
- src/components/ContactToPlace/helpers.js
- src/components/ContactToPlace/helpers.spec.js
- src/components/Providers/ContactToPlaceProvider.jsx
- src/constants.js
- src/lib/types.js
- src/locales/en.json
- src/locales/fr.json
Lorsque l'on lie un contact à un point de départ/arrivée, on peut indiquer un libellé.
Préalablement dans l'app CCO2, on stockait le `type` (qu'on appelait `label` dans le code) sur l'adresse et le label (qu'on appelait `category`) sur la clé `geo` de l'adresse.
Suite aux changements effectués sur l'app Contacts, il s'agit maintenant de stocker un `type` et un `label` (home|work) sur l'adresse.
```
* Store `type` and `label` address value when linking a contact to a start/end point.
```
> feat(ContactToPlace): Use `type` and `label` to set start/end point tag

- manifest.webapp
We used to run this service every hour to ensure to retrieve trips as soon as possible.
Now it can e triggered through a webhook  so it appears less necessary: the periodic execution might be useful just in case we missed the webhook execution for some reason.
Furthermore, having this very high frequency (hourly) is problematic in the objective to deploy this app on a large scale, as it results in producing a lot of jobs.
```
* Decrease periodic openpath fetching from hourly to daily
*
*
```
> feat: Decrease fetchOpenPathTrips frequency

- src/lib/recurringPurposes.js
- src/lib/recurringPurposes.spec.js
- src/queries/nodeQueries.js
We noticed issues in the address matching made in the recurring service, notably:
1. Errors on timeseries bulk saving
2. Address matching is restricted on account
For 1. we noticed errors in the logs, but with no way to know more about it, since the bulk save does not provide info.
Thus, we come back to the gool ol' document save.
For 2. we suspect that the multi-account feature was causing some side-effect. So we simply remove the account restriction and perform the matching on all timeseries.
```
* Recurring service now applies on all past trips, without account restriction
* Address matching 
*
```
> [DAT-59] fix: Address matching

- src/components/ContactToPlace/helpers.js
- src/lib/contacts.js
- src/lib/recurringPurposes.js
- src/lib/recurringPurposes.spec.js
- src/queries/nodeQueries.js
In the recurring service, we try to match an existing contact address for each trip start/end place.
When there are a lot of trips to process, this can result in many database IO and tend to make many conflicts since the few same contacts tend to be updated (e.g. myself).
So instead of updating each contact for each trip, we postpone the actual db save after all the trips are processed, and deduplicate the contacts update. For example, if the myself contact has an address with 100 match, we save it once instead of 100 times. 
```
*
* Minimize conflicts on recurring service 
* Minimize risks of recurring service timeout
*
```
> [DAT-57] [DAT-36] [DAT-48] Improve recurring service perfs

- .travis.yml
Transition to node 20 has been done successfuly on our production servers.
```
*
*
* Remove node 16 from tests in CI
* Remove stages in CI
```
> Remove node 16 from tests and stages in CI
